name: .NET Core

on:
  push:
    branches:
      - master
      - development
      - releases/*
      - features/*
      - fixes/*
  pull_request:
    branches: [ master,development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101  
        
    - name: Build
      run: dotnet build --configuration Release src/Ainject.applicationInsights
      
    - name: Test **/*[Tt]ests/*.csproj
      run: dotnet test --no-restore --verbosity normal src/Ainject.UnitTests
   
